xcodeproj 'NSMomentTests'
inhibit_all_warnings!

def import_pods
  pod 'Expecta', '~> 0.2.3'
  pod 'NSMoment', :path => '../'
end

target :ios do
  platform :ios, '5.0'
  link_with 'iOSTests'
  import_pods
end

target :osx do
  platform :osx, '10.8'
  link_with 'OSXTests'
  import_pods
end
