xcodeproj 'NSMomentTests'
inhibit_all_warnings!

def import_pods
  pod 'Expecta', '~> 0.2.3'
  pod 'NSMoment', :path => '../'
end

target :iOSTests do
  platform :ios, '5.0'
  import_pods
end

target :OSXTests do
  platform :osx, '10.8'
  import_pods
end
